### ISSUE TITLE
Error getting inventory

### ISSUE THREAD

**Issue by borisstock** [arangodb/elasticsearch-river-arangodb#4]
I'm getting this error:

```
[2016-02-24 12:51:51,311][WARN ][org.elasticsearch.river.arangodb.wal.states.CollectionCheck] Error getting inventory
java.net.ProtocolException: Too many follow-up requests: 21
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at net.swisstech.arangodb.WalClient.inventory(WalClient.java:49)
	at net.swisstech.arangodb.WalClient.inventory(WalClient.java:42)
	at org.elasticsearch.river.arangodb.wal.states.CollectionCheck.execute(CollectionCheck.java:50)
	at org.elasticsearch.river.arangodb.wal.WalReaderRunnable.run(WalReaderRunnable.java:40)
	at java.lang.Thread.run(Thread.java:745)

```
The collection I'm trying to index has more than 300'000 entries - is that a problem?

**Comment by borisstock** [comment]
Nevermind, found the problem - sorry! (password changed)

**Comment by Simran-B** [comment]
The error message ("Too many follow-up requests") is quite misleading
though. It should tell you that the password is incorrect in this case...
